version: '3.8'

services:
  app:
    restart: unless-stopped
    build: src
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 127.0.0.1:9432:80
    env_file:
      - .env
    volumes:
      - ./pgadmin_storage:/var/lib/pgadmin/storage/
